services:
  app:
    build:
      context: .
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: sh -c "npm run dev"

volumes:
  node_modules:
