import { Suspense } from "react";
import type { Metadata } from "next";

import "./globals.css";

import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import SideNavbar from "@/components/layout/side-navbar";
import { ThemeProvider } from "@/components/theme-provider";

import Loading from "./loading";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="mx-auto grid min-h-screen max-w-7xl grid-cols-10">
            <SideNavbar />
            <main className="col-span-8 w-full border-x border-slate-200 md:col-span-5">
              <Header />
              <Suspense fallback={<Loading />}>{children}</Suspense>
              <Footer />
            </main>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
